language: node_js
node_js:
  - "node"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
