language: node_js
node_js:
  - "node"

branches:
  only:
    - master

git:
  depth: 5

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - "node_modules"

before_deploy:
  - cp docs/index.html docs/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
