export const PROGRESS_TURN = 'PROGRESS_TURN';
export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const ALTER_ENCOUNTER_LIST = 'ALTER_ENCOUNTER_LIST';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
