export const PROGRESS_TURN = 'PROGRESS_TURN';
export const SAVE_CHARACTER = 'SAVE_CHARACTER';
export const ALTER_ENCOUNTER_LIST = 'ALTER_ENCOUNTER_LIST';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const SAVE_COMPLETE = 'SAVE_COMPLETE';
export const EDIT_CHARACTER = 'EDIT_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
